stages:
  - staging
  - production

# before_script: 
#   - eval $(ssh-agent -s)
#   - chmod 600 $SSH_PRIVATE_KEY
#   - ssh-add $SSH_PRIVATE_KEY

deploy_staging:
  stage: staging
  script:
  - eval $(ssh-agent -s)
  - chmod 600 $STAGING_SSH_PRIVATE_KEY
  - ssh-add $STAGING_SSH_PRIVATE_KEY
  - ssh $USER@$APP_URL_STAGING -o StrictHostKeyChecking=no ". ssh-restart.sh && ssh-add .ssh/chatsapi && cd frontend && git pull origin develop && docker-compose build dashboard && docker-compose up -d && exit"
  only:
    - develop

deploy_production:
  stage: production
  script:
  - eval $(ssh-agent -s)
  - chmod 600 $SSH_PRIVATE_KEY
  - ssh-add $SSH_PRIVATE_KEY
    - ssh $USER@$APP_URL -o StrictHostKeyChecking=no ". ssh-restart.sh && ssh-add .ssh/convexityApps && cd frontend-ngo-web && git pull origin production && docker-compose build dashboard && docker-compose up -d && exit"
  only:
    - production
