stages:
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - chmod 600 $SSH_PRIVATE_KEY
  - ssh-add $SSH_PRIVATE_KEY

deploy_staging:
  stage: deploy
  script:
    - ssh $USER@$APP_URL -o StrictHostKeyChecking=no ". ssh-restart.sh && ssh-add .ssh/convexityApps && cd frontend-ngo-web && git pull origin master && docker-compose build dashboard && docker-compose up -d && exit"
  only:
    - master
