version: "3.9"

services:
  dashboard:
    container_name: dashboard
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./:/dashboard
    ports:
      - 3000:3000
    networks:
      - gateway
    restart: unless-stopped

networks:
  gateway:
    driver: bridge
